name: suqi
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  badges: ^3.1.2
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.15.8
  convex_bottom_bar: ^3.2.0
  cupertino_icons: ^1.0.2
  dots_indicator: ^3.0.0
  firebase_analytics: 10.8.9
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  firebase_messaging: ^14.7.19
  firebase_storage: ^11.6.9
  firebase_storage_web: ^3.3.9
  floating_action_bubble: ^1.1.4
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_paypal_payment: ^1.0.6
  flutter_rating_bar: ^4.0.1
  flutter_swiper_null_safety: ^1.0.2
  font_awesome_flutter: ^10.7.0
  geocoding: ^3.0.0
  geolocator: ^11.1.0
  get_storage: ^2.1.1
  getwidget: ^4.0.0
  google_maps_flutter: ^2.5.3
  google_sign_in: ^6.2.1
  http: ^1.1.0
  image_picker: ^1.0.7
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  is_first_run: ^1.0.0
  liquid_swipe: ^3.1.0
  loading_animation_widget: ^1.2.1
  location: ^5.0.3
  permission_handler: ^11.1.1
  photo_view: ^0.14.0
  provider: ^6.1.2
dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#8DC73F"
  adaptive_icon_foreground: "assets/images/logo.png"
  # dependency_overrides:
  # firebase_core_platform_interface: 4.5.1
flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Mada
      fonts:
        - asset: assets/fonts/Mada-Bold.ttf
          weight: 900
        - asset: assets/fonts/Mada-Medium.ttf
          weight: 300
        - asset: assets/fonts/Mada-Regular.ttf
